spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  security:
    user:
      name: blog
      password: admin123

  main:
    allow-circular-references: true

server:
  error:
    whitelabel:
      enabled: false

logging:
  level:
    com:
      example:
        blog:
          controller: TRACE