INSERT INTO roles(role) VALUES ('USER');
INSERT INTO roles(role) VALUES ('ADMIN');

INSERT INTO users(name, last_name, email, phone_number, home_address, username, password) VALUES ('Vytas', 'Vytauskas', 'vytukas@yahoo.com', '+37064294226', 'Liepų g. 7, Kaunas', 'administrator', '$2a$12$h7IrjjBWq1C1NWOD2SdSNeyZyAQpIGDl/rjNmP0dV3M95dVvP/VhO');
INSERT INTO users(name, last_name, email, phone_number, home_address, username, password) VALUES ('Saulius', 'Sauliunas', 'sauliukas@gmail.com', '+37068524220', 'Vilniaus g. 24, Kaunas', 'saulenas', '$2a$12$h7IrjjBWq1C1NWOD2SdSNeyZyAQpIGDl/rjNmP0dV3M95dVvP/VhO');

INSERT INTO users_roles(user_id, roles_id) VALUES (1, 1);
INSERT INTO users_roles(user_id, roles_id) VALUES (1, 2);

INSERT INTO users_roles(user_id, roles_id) VALUES(2, 1);

INSERT INTO post(title, posted_text, post_time, user_id) VALUES ('Taivanas', 'Prekybai tarp Lietuvos ir Taivano augant, verslo atstovas dar neskuba džiaugtis. Anot jo, Kinijos praradimų tai vis tiek neatsvers, buvo padaryta klaida, o ir dėl dabartinių projektų su Taivanu kol kas nieko konkretaus nėra sutarta. Tačiau kita pusė atkerta, kad verslo ateitis – ne darbas su nedemokratiška Kinija Skaitykite daugiau', '2019-01-21T05:47:08.644', 1);
INSERT INTO post(title, posted_text, post_time, user_id) VALUES ('Vienaragis', 'Ką mes šiandien dienai gavome, jų rinkos kaip ir nelabai turime arba turime simbolinį padidėjimą, gavome keliasdešimt stipendijų mūsų studentams studijuoti ir viskas tuo baigėsi. Nenoriu pasakyti, kad čia vien Taivano problema. Tai ir mūsų. Labai daug tenka bendrauti su taivaniečiais ir ką išgirstu sako, galit ant pirštų pasakyti norus, ko norit šiai dienai, kaip bendradarbiavimą padidinti, nes jie mato daug politikų delegacijų, gražiai šneka, bendradarbiausim, prioritetinė šalis, skatinsim demokratiją, bet tų šnekų mes ir taip daug girdime, jos niekur neveda“, – kalbėjo S. Besagirskas pabrėždamas, kad reikia, jog į Taivaną pradėtų vykti verslo delegacijos, įsitrauktų daugiau įmonių.', '2022-01-21T05:47:08.644', 2);
INSERT INTO post(title, posted_text, post_time, user_id) VALUES ('Verslas', 'Mes kalbame apie rinkos atvėrimą suprantant geopolitinę situaciją, nes verslas, kaip ir politika, visada yra apie ateitį ir ateitis nėra Kinijoje. Tai jau suprato vokiečių verslas, ES verslas, jis ieško kelių ir išeidinėja iš ten, nes supranta, su kuo susiduria. Tai kas dabar Rusijoje, laiko klausimas, kai tai bus su Kinija. (…) Labai didelės perspektyvos (Taivano – „Delfi“) ir galime turėti labai gerų žinių. Ne tai, kad kažko neduos, kodėl važiuoja studentai ten. Argi taivaniečiai tokie kvaili? Jie ima studentus ne šiaip sau, jie ima studentus, nes jie atvažiavo į Lietuvą ir pamatė, kad turime problemų su mūsų švietimo sistema. Jie gali mums kažką pasiūlyti, bet mes nesame paruošę žmonių, kurie galėtų dirbti tose gamyklose, atėjus investicijoms. Jie veža ten juos apmokinti, kad po to čia grįžę, kai ateis verslas, galėtų mokyti ir kitus. Būti tie, kurie įgyvendins tuos projektus.', '2022-03-21T08:47:08.644', 2);
INSERT INTO post(title, posted_text, post_time, user_id) VALUES ('Ekonomika', 'Ekonomistas Aleksandras Izgorodinas kiek anksčiau naujienų agentūrai „Elta“ komentavo, kad nuo 2021 m. lapkričio, kuomet Vilniuje buvo atidaryta taivaniečių atstovybė, tarpusavio prekyba, lyginant su fiksuota analogišku laikotarpiu metais anksčiau, išaugo nuo 29,3 mln, iki 46,3 mln. eurų Skaitykite ', '2022-04-21T05:47:08.644', 1);
INSERT INTO post(title, posted_text, post_time, user_id) VALUES ('Kinija', 'Svarbu paminėti, kalbant apie Kinijos užsivėrimą, tai 300 mln. eurų, ir bendra situacija, kurią turime, tai turime suprasti, kad mums uždarius Kinijos rinką, jos nelegalus veiksmas, reaguodama į tai JAV atidarė savo rinką. Tai nebuvo sutapimas, kad staiga mes ten smarkiai pradėjome eksportuoti. Per pirmus šių metų tris mėnesius, Lietuva į JAV eksportavo dvigubai daugiau nei į Kiniją per visus metus geriausiais laikais. Į JAV eksportuota už 600 mln., per tris mėnesius augimas 25 proc.“, – kalbėjo jis.', '2022-01-21T05:47:08.644', 2);
INSERT INTO post(title, posted_text, post_time, user_id) VALUES ('Kitos rinkos', 'Kitos rinkos – Singapūras, Australija, Pietų Korėja, tai nelabai susiję su Taivanu. Ką reiškia eksportas į JAV? Turėjome dvi rinkas, kur eksportavome su 20-30 proc., o kartais net 100 proc. marža. Tai buvo Rusija ir Kinija. Rusija, suprantame objektyviai, sveiko proto žmogus tikrai nedraugaus su Rusija', '2022-03-21T08:47:08.644', 2);
INSERT INTO post(title, posted_text, post_time, user_id) VALUES ('Įmonės', 'Vienoms įmonėms gerai, kitos kol kas negali atsivežti kiniškos produkcijos, bet tai yra lengvai išsprendžiama. Moki 30 proc. daugiau ir iš sandėlio Vokietijoje ar Lenkijoje nusiperki. O su eksportu viskas stoja. Pagrindinė problema marža. Jei kolega sako apie pridėtinę vertę, didelį darbo užmokestį, tai tu turi parduoti į tas rinkas, kur daug uždirbi.', '2022-02-21T05:47:08.644', 1);
INSERT INTO post(title, posted_text, post_time, user_id) VALUES ('Lietuvos veiksmai', 'Ką Lietuva padarė ne taip, kad susilaukė tokios Kinijos reakcijos? Tai buvo vidaus politikos reikalai, pavyzdys kitoms ES šalims kas atsitinka su Kinija. Ar Norvegija, Australija padarė klaidą Kinijos atžvilgiu? Per paskutinius dešimt metų Kinija yra įvedus 170 sankcijų valstybėms. Ar visos jos padarė klaidą ar kažkas yra su Kinija?“, – kėlė klausimus jis. ', '2022-01-21T05:47:08.644', 2);
INSERT INTO post(title, posted_text, post_time, user_id) VALUES ('Komentaras', 'Mes dabar didelį daiktą apmėtėme supusiais pomidorais, stipriai gavome atgal. Kinija nuo to stipri pasijautė, mes nuo to negavome nieko. Tai infantili politika. Bent jau reikėjo dvišalių derybų, išsiaiškinti, ar atstovybės pavadinime vienas ar kitas žodis Taivanui reikalingas. Gal galėjome pavadinti Taipėjaus atstovybe ir neprarasti to eksporto, to potencialo, kurį turėjome šiai dienai“, – teigia S. Besagirskas', '2022-04-21T08:47:08.644', 2);